services:
  demon-db:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=demoncells
    volumes:
      - db_data:/bitnami/postgresql
    restart: unless-stopped
  
volumes:
  db_data:
